language: php

services:
  - docker

php:
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"

script:
  - docker run -v $PWD:/work -w /work byjg/php:${TRAVIS_PHP_VERSION}-cli composer install && vendor/bin/phpunit
